name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: cargo build --locked

      - name: Run unit tests
        run: RUSTFLAGS=-Awarnings cargo test --lib --bins --test unit -- --test-threads=1

      - name: Run integration tests
        run: RUSTFLAGS=-Awarnings cargo test --test integration -- --test-threads=1

  e2e-longrunning:
    runs-on: ubuntu-latest
    # needs: test  # Only run after main tests pass
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: cargo build --locked

      - name: Run end-to-end long-running tests
        run: cargo test --test e2e_longrunning e2e_performance_benchmark -- --test-threads=1 --nocapture
        timeout-minutes: 30  # Allow up to 30 minutes for long-running tests // IOPS is fucked on CI I guess lmao
